version: "1.0"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: api
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
